import { Product, Order, Activity, RevenueData, ReadingType, ReadingBooking, ReadingAvailability } from "./types";

export const products: Product[] = [
  // Originals (3)
  {
    id: "p1",
    sku: "OG-001",
    name: "Amberish Absolute Intense",
    collection: "Originals",
    price: 85,
    stock: 24,
    status: "in-stock",
    size: "50ml",
  },
  {
    id: "p2",
    sku: "OG-002",
    name: "Velvet Tonka",
    collection: "Originals",
    price: 78,
    stock: 3,
    status: "low-stock",
    size: "50ml",
  },
  {
    id: "p3",
    sku: "OG-003",
    name: "Oud Saffron Noir",
    collection: "Originals",
    price: 95,
    stock: 18,
    status: "in-stock",
    size: "50ml",
  },
  // Perito Moreno Luxury (2)
  {
    id: "p4",
    sku: "PM-001",
    name: "Glacial Iris",
    collection: "Perito Moreno Luxury",
    price: 160,
    stock: 8,
    status: "in-stock",
    size: "100ml",
  },
  {
    id: "p5",
    sku: "PM-002",
    name: "Patagonia Leather",
    collection: "Perito Moreno Luxury",
    price: 145,
    stock: 0,
    status: "out-of-stock",
    size: "100ml",
  },
  // PM Decants (2)
  {
    id: "p6",
    sku: "PMD-001",
    name: "Glacial Iris (Decant)",
    collection: "PM Decants",
    price: 32,
    stock: 45,
    status: "in-stock",
    size: "10ml",
  },
  {
    id: "p7",
    sku: "PMD-002",
    name: "Patagonia Leather (Decant)",
    collection: "PM Decants",
    price: 28,
    stock: 5,
    status: "low-stock",
    size: "10ml",
  },
  // Dark Tales (3)
  {
    id: "p8",
    sku: "DT-001",
    name: "Crimson Absinthe",
    collection: "Dark Tales",
    price: 72,
    stock: 12,
    status: "in-stock",
    size: "50ml",
  },
  {
    id: "p9",
    sku: "DT-002",
    name: "Midnight Laudanum",
    collection: "Dark Tales",
    price: 68,
    stock: 0,
    status: "out-of-stock",
    size: "50ml",
  },
  {
    id: "p10",
    sku: "DT-003",
    name: "Phantom Smoke",
    collection: "Dark Tales",
    price: 65,
    stock: 2,
    status: "low-stock",
    size: "30ml",
  },
  // Aromas De Salazar (2)
  {
    id: "p11",
    sku: "ADS-001",
    name: "Rosa del Conquistador",
    collection: "Aromas De Salazar",
    price: 52,
    stock: 30,
    status: "in-stock",
    size: "50ml",
  },
  {
    id: "p12",
    sku: "ADS-002",
    name: "Tabaco y Vainilla",
    collection: "Aromas De Salazar",
    price: 22,
    stock: 60,
    status: "in-stock",
    size: "30ml",
  },
];

export const orders: Order[] = [
  {
    id: "ORD-1047",
    customer: "Elena Marchetti",
    email: "elena.m@email.com",
    items: [
      { name: "Amberish Absolute Intense", quantity: 1, price: 85 },
      { name: "Glacial Iris (Decant)", quantity: 2, price: 32 },
    ],
    total: 149,
    status: "delivered",
    date: "2026-03-02",
  },
  {
    id: "ORD-1046",
    customer: "James Whitfield",
    email: "j.whitfield@email.com",
    items: [{ name: "Glacial Iris", quantity: 1, price: 160 }],
    total: 160,
    status: "shipped",
    date: "2026-03-01",
  },
  {
    id: "ORD-1045",
    customer: "Sofia Reyes",
    email: "sofia.r@email.com",
    items: [
      { name: "Crimson Absinthe", quantity: 1, price: 72 },
      { name: "Phantom Smoke", quantity: 1, price: 65 },
    ],
    total: 137,
    status: "pending",
    date: "2026-03-01",
  },
  {
    id: "ORD-1044",
    customer: "David Chen",
    email: "dchen@email.com",
    items: [
      { name: "Oud Saffron Noir", quantity: 1, price: 95 },
      { name: "Patagonia Leather (Decant)", quantity: 1, price: 28 },
    ],
    total: 123,
    status: "processing",
    date: "2026-02-28",
  },
  {
    id: "ORD-1043",
    customer: "Amara Okafor",
    email: "amara.o@email.com",
    items: [{ name: "Velvet Tonka", quantity: 1, price: 78 }],
    total: 78,
    status: "delivered",
    date: "2026-02-27",
  },
  {
    id: "ORD-1042",
    customer: "Lucas Petrov",
    email: "lpetrov@email.com",
    items: [
      { name: "Rosa del Conquistador", quantity: 2, price: 52 },
      { name: "Tabaco y Vainilla", quantity: 3, price: 22 },
    ],
    total: 170,
    status: "delivered",
    date: "2026-02-25",
  },
  {
    id: "ORD-1041",
    customer: "Isabelle Fontaine",
    email: "i.fontaine@email.com",
    items: [{ name: "Patagonia Leather", quantity: 1, price: 145 }],
    total: 145,
    status: "cancelled",
    date: "2026-02-24",
  },
  {
    id: "ORD-1040",
    customer: "Marco Benedetti",
    email: "marco.b@email.com",
    items: [
      { name: "Amberish Absolute Intense", quantity: 2, price: 85 },
      { name: "Midnight Laudanum", quantity: 1, price: 68 },
    ],
    total: 238,
    status: "delivered",
    date: "2026-02-22",
  },
  {
    id: "ORD-1039",
    customer: "Priya Sharma",
    email: "priya.s@email.com",
    items: [{ name: "Tabaco y Vainilla", quantity: 1, price: 22 }],
    total: 22,
    status: "pending",
    date: "2026-02-20",
  },
  {
    id: "ORD-1038",
    customer: "Oliver Krauss",
    email: "okrauss@email.com",
    items: [
      { name: "Glacial Iris", quantity: 1, price: 160 },
      { name: "Oud Saffron Noir", quantity: 1, price: 95 },
    ],
    total: 255,
    status: "shipped",
    date: "2026-02-18",
  },
];

export const activities: Activity[] = [
  { id: "a1", type: "order", message: "New order #ORD-1047 from Elena Marchetti", time: "2 hours ago" },
  { id: "a2", type: "stock", message: "Velvet Tonka stock low — 3 units remaining", time: "5 hours ago" },
  { id: "a3", type: "order", message: "Order #ORD-1046 shipped via DHL Express", time: "8 hours ago" },
  { id: "a4", type: "review", message: "New 5-star review on Amberish Absolute Intense", time: "1 day ago" },
  { id: "a5", type: "stock", message: "Patagonia Leather now out of stock", time: "1 day ago" },
  { id: "a6", type: "system", message: "Monthly revenue report generated", time: "2 days ago" },
  { id: "a7", type: "order", message: "Order #ORD-1041 cancelled by customer", time: "3 days ago" },
  { id: "a8", type: "review", message: "New 4-star review on Crimson Absinthe", time: "3 days ago" },
];

export const revenueData: RevenueData[] = [
  { month: "Sep", revenue: 3200 },
  { month: "Oct", revenue: 4100 },
  { month: "Nov", revenue: 5800 },
  { month: "Dec", revenue: 7200 },
  { month: "Jan", revenue: 4900 },
  { month: "Feb", revenue: 6100 },
  { month: "Mar", revenue: 2800 },
];

export const collections = [
  "Originals",
  "Perito Moreno Luxury",
  "PM Decants",
  "Dark Tales",
  "Aromas De Salazar",
];

export const readingTypes: ReadingType[] = [
  {
    id: "rt-1",
    name: "Intuitive Fragrance Reading",
    tagline: "Discover your scent identity",
    price: 50,
    active: true,
    description: [
      "One-on-one 30-minute session with Jamie",
      "Personalized scent profile based on your energy",
      "Three curated fragrance recommendations",
      "Digital scent journal to take home",
    ],
  },
  {
    id: "rt-2",
    name: "Channeled Healing Session",
    tagline: "Fragrance as medicine for the soul",
    price: 150,
    active: true,
    description: [
      "Deep 60-minute guided aromatic journey",
      "Chakra-aligned fragrance mapping",
      "Custom healing blend created during session",
      "Follow-up email with integration guidance",
    ],
  },
];

export const readingAvailability: ReadingAvailability = {
  activeDays: [1, 2, 3, 4, 5],
  timeSlots: ["10:00 AM", "12:00 PM", "2:00 PM", "4:00 PM"],
  blockedDates: ["2026-03-17", "2026-03-25"],
};

export const readingBookings: ReadingBooking[] = [
  {
    id: "RB-001",
    clientName: "Aria Belmont",
    clientEmail: "aria.b@email.com",
    readingType: "Intuitive Fragrance Reading",
    date: "2026-03-06",
    timeSlot: "10:00 AM",
    status: "confirmed",
    notes: "Interested in woody scents",
    createdAt: "2026-03-01",
  },
  {
    id: "RB-002",
    clientName: "Marcus Delgado",
    clientEmail: "m.delgado@email.com",
    readingType: "Channeled Healing Session",
    date: "2026-03-07",
    timeSlot: "2:00 PM",
    status: "pending",
    notes: "",
    createdAt: "2026-03-02",
  },
  {
    id: "RB-003",
    clientName: "Lena Voronova",
    clientEmail: "lena.v@email.com",
    readingType: "Intuitive Fragrance Reading",
    date: "2026-03-03",
    timeSlot: "12:00 PM",
    status: "completed",
    notes: "Loved the session! Wants to rebook.",
    createdAt: "2026-02-25",
  },
  {
    id: "RB-004",
    clientName: "Theo Ashford",
    clientEmail: "theo.a@email.com",
    readingType: "Channeled Healing Session",
    date: "2026-03-10",
    timeSlot: "4:00 PM",
    status: "confirmed",
    notes: "First time client, referred by Lena",
    createdAt: "2026-03-03",
  },
  {
    id: "RB-005",
    clientName: "Nina Castillo",
    clientEmail: "nina.c@email.com",
    readingType: "Intuitive Fragrance Reading",
    date: "2026-03-05",
    timeSlot: "10:00 AM",
    status: "cancelled",
    notes: "Scheduling conflict",
    createdAt: "2026-02-28",
  },
];
