import { Product, Order, Activity, RevenueData, ReadingType, ReadingBooking, ReadingAvailability, EmailCampaign, LoyaltyTier, LoyaltyMember, PointRedemption } from "./types";

export const products: Product[] = [
  // Originals (3)
  {
    id: "p1",
    sku: "OG-001",
    name: "Amberish Absolute Intense",
    collection: "Originals",
    price: 85,
    stock: 24,
    status: "in-stock",
    size: "50ml",
  },
  {
    id: "p2",
    sku: "OG-002",
    name: "Velvet Tonka",
    collection: "Originals",
    price: 78,
    stock: 3,
    status: "low-stock",
    size: "50ml",
  },
  {
    id: "p3",
    sku: "OG-003",
    name: "Oud Saffron Noir",
    collection: "Originals",
    price: 95,
    stock: 18,
    status: "in-stock",
    size: "50ml",
  },
  // Perito Moreno Luxury (2)
  {
    id: "p4",
    sku: "PM-001",
    name: "Glacial Iris",
    collection: "Perito Moreno Luxury",
    price: 160,
    stock: 8,
    status: "in-stock",
    size: "100ml",
  },
  {
    id: "p5",
    sku: "PM-002",
    name: "Patagonia Leather",
    collection: "Perito Moreno Luxury",
    price: 145,
    stock: 0,
    status: "out-of-stock",
    size: "100ml",
  },
  // PM Decants (2)
  {
    id: "p6",
    sku: "PMD-001",
    name: "Glacial Iris (Decant)",
    collection: "PM Decants",
    price: 32,
    stock: 45,
    status: "in-stock",
    size: "10ml",
  },
  {
    id: "p7",
    sku: "PMD-002",
    name: "Patagonia Leather (Decant)",
    collection: "PM Decants",
    price: 28,
    stock: 5,
    status: "low-stock",
    size: "10ml",
  },
  // Dark Tales (3)
  {
    id: "p8",
    sku: "DT-001",
    name: "Crimson Absinthe",
    collection: "Dark Tales",
    price: 72,
    stock: 12,
    status: "in-stock",
    size: "50ml",
  },
  {
    id: "p9",
    sku: "DT-002",
    name: "Midnight Laudanum",
    collection: "Dark Tales",
    price: 68,
    stock: 0,
    status: "out-of-stock",
    size: "50ml",
  },
  {
    id: "p10",
    sku: "DT-003",
    name: "Phantom Smoke",
    collection: "Dark Tales",
    price: 65,
    stock: 2,
    status: "low-stock",
    size: "30ml",
  },
  // Aromas De Salazar (2)
  {
    id: "p11",
    sku: "ADS-001",
    name: "Rosa del Conquistador",
    collection: "Aromas De Salazar",
    price: 52,
    stock: 30,
    status: "in-stock",
    size: "50ml",
  },
  {
    id: "p12",
    sku: "ADS-002",
    name: "Tabaco y Vainilla",
    collection: "Aromas De Salazar",
    price: 22,
    stock: 60,
    status: "in-stock",
    size: "30ml",
  },
];

export const orders: Order[] = [
  {
    id: "ORD-1047",
    customer: "Elena Marchetti",
    email: "elena.m@email.com",
    items: [
      { name: "Amberish Absolute Intense", quantity: 1, price: 85 },
      { name: "Glacial Iris (Decant)", quantity: 2, price: 32 },
    ],
    total: 149,
    status: "delivered",
    date: "2026-03-02",
  },
  {
    id: "ORD-1046",
    customer: "James Whitfield",
    email: "j.whitfield@email.com",
    items: [{ name: "Glacial Iris", quantity: 1, price: 160 }],
    total: 160,
    status: "shipped",
    date: "2026-03-01",
  },
  {
    id: "ORD-1045",
    customer: "Sofia Reyes",
    email: "sofia.r@email.com",
    items: [
      { name: "Crimson Absinthe", quantity: 1, price: 72 },
      { name: "Phantom Smoke", quantity: 1, price: 65 },
    ],
    total: 137,
    status: "pending",
    date: "2026-03-01",
  },
  {
    id: "ORD-1044",
    customer: "David Chen",
    email: "dchen@email.com",
    items: [
      { name: "Oud Saffron Noir", quantity: 1, price: 95 },
      { name: "Patagonia Leather (Decant)", quantity: 1, price: 28 },
    ],
    total: 123,
    status: "processing",
    date: "2026-02-28",
  },
  {
    id: "ORD-1043",
    customer: "Amara Okafor",
    email: "amara.o@email.com",
    items: [{ name: "Velvet Tonka", quantity: 1, price: 78 }],
    total: 78,
    status: "delivered",
    date: "2026-02-27",
  },
  {
    id: "ORD-1042",
    customer: "Lucas Petrov",
    email: "lpetrov@email.com",
    items: [
      { name: "Rosa del Conquistador", quantity: 2, price: 52 },
      { name: "Tabaco y Vainilla", quantity: 3, price: 22 },
    ],
    total: 170,
    status: "delivered",
    date: "2026-02-25",
  },
  {
    id: "ORD-1041",
    customer: "Isabelle Fontaine",
    email: "i.fontaine@email.com",
    items: [{ name: "Patagonia Leather", quantity: 1, price: 145 }],
    total: 145,
    status: "cancelled",
    date: "2026-02-24",
  },
  {
    id: "ORD-1040",
    customer: "Marco Benedetti",
    email: "marco.b@email.com",
    items: [
      { name: "Amberish Absolute Intense", quantity: 2, price: 85 },
      { name: "Midnight Laudanum", quantity: 1, price: 68 },
    ],
    total: 238,
    status: "delivered",
    date: "2026-02-22",
  },
  {
    id: "ORD-1039",
    customer: "Priya Sharma",
    email: "priya.s@email.com",
    items: [{ name: "Tabaco y Vainilla", quantity: 1, price: 22 }],
    total: 22,
    status: "pending",
    date: "2026-02-20",
  },
  {
    id: "ORD-1038",
    customer: "Oliver Krauss",
    email: "okrauss@email.com",
    items: [
      { name: "Glacial Iris", quantity: 1, price: 160 },
      { name: "Oud Saffron Noir", quantity: 1, price: 95 },
    ],
    total: 255,
    status: "shipped",
    date: "2026-02-18",
  },
];

export const activities: Activity[] = [
  { id: "a1", type: "order", message: "New order #ORD-1047 from Elena Marchetti", time: "2 hours ago" },
  { id: "a2", type: "stock", message: "Velvet Tonka stock low — 3 units remaining", time: "5 hours ago" },
  { id: "a3", type: "order", message: "Order #ORD-1046 shipped via DHL Express", time: "8 hours ago" },
  { id: "a4", type: "review", message: "New 5-star review on Amberish Absolute Intense", time: "1 day ago" },
  { id: "a5", type: "stock", message: "Patagonia Leather now out of stock", time: "1 day ago" },
  { id: "a6", type: "system", message: "Monthly revenue report generated", time: "2 days ago" },
  { id: "a7", type: "order", message: "Order #ORD-1041 cancelled by customer", time: "3 days ago" },
  { id: "a8", type: "review", message: "New 4-star review on Crimson Absinthe", time: "3 days ago" },
];

export const revenueData: RevenueData[] = [
  { month: "Sep", revenue: 3200 },
  { month: "Oct", revenue: 4100 },
  { month: "Nov", revenue: 5800 },
  { month: "Dec", revenue: 7200 },
  { month: "Jan", revenue: 4900 },
  { month: "Feb", revenue: 6100 },
  { month: "Mar", revenue: 2800 },
];

export const collections = [
  "Originals",
  "Perito Moreno Luxury",
  "PM Decants",
  "Dark Tales",
  "Aromas De Salazar",
];

export const readingTypes: ReadingType[] = [
  {
    id: "rt-1",
    name: "Intuitive Fragrance Reading",
    tagline: "Discover your scent identity",
    price: 50,
    active: true,
    description: [
      "One-on-one 30-minute session with Jamie",
      "Personalized scent profile based on your energy",
      "Three curated fragrance recommendations",
      "Digital scent journal to take home",
    ],
  },
  {
    id: "rt-2",
    name: "Channeled Healing Session",
    tagline: "Fragrance as medicine for the soul",
    price: 150,
    active: true,
    description: [
      "Deep 60-minute guided aromatic journey",
      "Chakra-aligned fragrance mapping",
      "Custom healing blend created during session",
      "Follow-up email with integration guidance",
    ],
  },
];

export const readingAvailability: ReadingAvailability = {
  activeDays: [1, 2, 3, 4, 5],
  timeSlots: ["10:00 AM", "12:00 PM", "2:00 PM", "4:00 PM"],
  blockedDates: ["2026-03-17", "2026-03-25"],
};

export const readingBookings: ReadingBooking[] = [
  {
    id: "RB-001",
    clientName: "Aria Belmont",
    clientEmail: "aria.b@email.com",
    readingType: "Intuitive Fragrance Reading",
    date: "2026-03-06",
    timeSlot: "10:00 AM",
    status: "confirmed",
    notes: "Interested in woody scents",
    createdAt: "2026-03-01",
  },
  {
    id: "RB-002",
    clientName: "Marcus Delgado",
    clientEmail: "m.delgado@email.com",
    readingType: "Channeled Healing Session",
    date: "2026-03-07",
    timeSlot: "2:00 PM",
    status: "pending",
    notes: "",
    createdAt: "2026-03-02",
  },
  {
    id: "RB-003",
    clientName: "Lena Voronova",
    clientEmail: "lena.v@email.com",
    readingType: "Intuitive Fragrance Reading",
    date: "2026-03-03",
    timeSlot: "12:00 PM",
    status: "completed",
    notes: "Loved the session! Wants to rebook.",
    createdAt: "2026-02-25",
  },
  {
    id: "RB-004",
    clientName: "Theo Ashford",
    clientEmail: "theo.a@email.com",
    readingType: "Channeled Healing Session",
    date: "2026-03-10",
    timeSlot: "4:00 PM",
    status: "confirmed",
    notes: "First time client, referred by Lena",
    createdAt: "2026-03-03",
  },
  {
    id: "RB-005",
    clientName: "Nina Castillo",
    clientEmail: "nina.c@email.com",
    readingType: "Intuitive Fragrance Reading",
    date: "2026-03-05",
    timeSlot: "10:00 AM",
    status: "cancelled",
    notes: "Scheduling conflict",
    createdAt: "2026-02-28",
  },
];

export const loyaltyTiers: LoyaltyTier[] = [
  { id: "t1", name: "Bronze", minPoints: 0, discount: 5, color: "#8b5e3c" },
  { id: "t2", name: "Silver", minPoints: 500, discount: 10, color: "#7a6e62" },
  { id: "t3", name: "Gold", minPoints: 1500, discount: 15, color: "#8a6218" },
  { id: "t4", name: "Platinum", minPoints: 5000, discount: 25, color: "#2a5060" },
];

export const loyaltyMembers: LoyaltyMember[] = [
  { id: "LM-001", name: "Elena Marchetti", email: "elena.m@email.com", tier: "gold", points: 2340, totalSpent: 892, joinDate: "2025-06-15", lastActivity: "2026-03-02", status: "active" },
  { id: "LM-002", name: "James Whitfield", email: "j.whitfield@email.com", tier: "platinum", points: 6120, totalSpent: 2450, joinDate: "2025-01-10", lastActivity: "2026-03-01", status: "active" },
  { id: "LM-003", name: "Sofia Reyes", email: "sofia.r@email.com", tier: "silver", points: 780, totalSpent: 345, joinDate: "2025-09-22", lastActivity: "2026-03-01", status: "active" },
  { id: "LM-004", name: "David Chen", email: "dchen@email.com", tier: "gold", points: 1890, totalSpent: 756, joinDate: "2025-04-18", lastActivity: "2026-02-28", status: "active" },
  { id: "LM-005", name: "Amara Okafor", email: "amara.o@email.com", tier: "bronze", points: 210, totalSpent: 78, joinDate: "2025-12-01", lastActivity: "2026-02-27", status: "active" },
  { id: "LM-006", name: "Lucas Petrov", email: "lpetrov@email.com", tier: "silver", points: 540, totalSpent: 412, joinDate: "2025-07-30", lastActivity: "2026-02-25", status: "active" },
  { id: "LM-007", name: "Isabelle Fontaine", email: "i.fontaine@email.com", tier: "bronze", points: 90, totalSpent: 145, joinDate: "2025-11-05", lastActivity: "2025-12-14", status: "inactive" },
  { id: "LM-008", name: "Marco Benedetti", email: "marco.b@email.com", tier: "platinum", points: 5430, totalSpent: 1980, joinDate: "2024-11-20", lastActivity: "2026-02-22", status: "active" },
];

export const pointRedemptions: PointRedemption[] = [
  { id: "PR-001", memberId: "LM-002", memberName: "James Whitfield", type: "exclusive-access", pointsSpent: 1000, description: "Early access to Perito Moreno Luxury launch", date: "2026-03-01" },
  { id: "PR-002", memberId: "LM-001", memberName: "Elena Marchetti", type: "discount", pointsSpent: 500, description: "15% off next purchase", date: "2026-02-28" },
  { id: "PR-003", memberId: "LM-004", memberName: "David Chen", type: "free-product", pointsSpent: 800, description: "Free Patagonia Leather Decant (10ml)", date: "2026-02-25" },
  { id: "PR-004", memberId: "LM-008", memberName: "Marco Benedetti", type: "exclusive-access", pointsSpent: 1500, description: "Private fragrance consultation with Jamie", date: "2026-02-20" },
  { id: "PR-005", memberId: "LM-003", memberName: "Sofia Reyes", type: "discount", pointsSpent: 300, description: "10% off Dark Tales collection", date: "2026-02-18" },
  { id: "PR-006", memberId: "LM-006", memberName: "Lucas Petrov", type: "free-product", pointsSpent: 400, description: "Free Glacial Iris sample set", date: "2026-02-15" },
];

export const emailCampaigns: EmailCampaign[] = [
  {
    id: "EC-001",
    name: "Spring Collection Launch",
    subject: "Introducing our Spring 2026 fragrances",
    status: "sent",
    audience: "all-customers",
    sentDate: "2026-02-15",
    openRate: 42.3,
    clickRate: 12.8,
    recipientCount: 1847,
    body: "Discover the enchanting new scents of our Spring 2026 collection, featuring floral and citrus notes inspired by Mediterranean gardens.",
  },
  {
    id: "EC-002",
    name: "VIP Exclusive: Perito Moreno Preview",
    subject: "You're invited — first look at Perito Moreno Luxury",
    status: "sent",
    audience: "vip",
    sentDate: "2026-02-22",
    openRate: 68.1,
    clickRate: 31.4,
    recipientCount: 214,
    body: "As a valued VIP customer, get exclusive early access to our Perito Moreno Luxury line before it launches to the public.",
  },
  {
    id: "EC-003",
    name: "March Newsletter",
    subject: "What's new at Polysnifferous this March",
    status: "scheduled",
    audience: "all-customers",
    scheduledDate: "2026-03-10",
    recipientCount: 1923,
    body: "Your monthly roundup of new arrivals, reading availability, and behind-the-scenes stories from the Polysnifferous atelier.",
  },
  {
    id: "EC-004",
    name: "Win-Back: We Miss You",
    subject: "It's been a while — here's 15% off your next order",
    status: "paused",
    audience: "repeat-customers",
    scheduledDate: "2026-03-05",
    recipientCount: 432,
    body: "We noticed you haven't visited in a while. Come back and enjoy 15% off any full-size fragrance with code MISSYOU15.",
  },
  {
    id: "EC-005",
    name: "New Customer Welcome Series",
    subject: "Welcome to the Polysnifferous family",
    status: "draft",
    audience: "new-customers",
    recipientCount: 0,
    body: "A warm welcome to new subscribers — introduce them to our story, best sellers, and reading sessions.",
  },
  {
    id: "EC-006",
    name: "Dark Tales Teaser",
    subject: "Something wicked this way comes...",
    status: "draft",
    audience: "all-customers",
    recipientCount: 0,
    body: "Build anticipation for the upcoming Dark Tales limited edition release with mysterious imagery and scent descriptions.",
  },
];
